name: HGkits-NormalKits
main: SpecialKits\Loader
version: 0.0
api:
- 1.12.0
- 1.13.0
- 2.0.0

load: POSTWORLD
author: RedstoneAlmeida
description: HungerGames Kits!
website: https://github.com/PocketSoftMine/HGKits
commands:
 normalkits:
  description: NormalKits
  use: "/normalkits"
  permission: normalkits.command
permissions:
 normalkits.command:
  description: "NormalKist"
  default: false
