name: HGKits-SpecialKits
main: SpecialKits\Main
version: 0.8
api:
- 2.0.0
- 3.0.0
- 4.0.0
author: RedstoneAlmeida, AnnonymousGames, erkam2002
description: "HungerGames Kits!"
website: https://github.com/PocketSoftMine/HGKits
commands:
  kits:
    description: Kits
    usage: "/kits"
    permission: kits.command
  stomper:
    description: StomperKit
    usage: "/stomper"
    permission: stomperkit.command
  endermage:
    description: EnderMageKit
    usage: "/endermage"
    permission: endermage.command
  kangaruu:
    description: KangaruuKit
    usage: "/kangaruu"
    permission: kangaruu.command
  switcher:
    description: SwitcherKit
    usage: "/switcher"
    permission: switcher.command
  urgal:
    description: UrgalKit
    usage: "/urgal"
    permission: urgal.command
  miner:
    description: MinerKit
    usage: "/miner"
    permission: miner.command
  life:
    description: LifeKit
    usage: "/life"
    permission: life.command
  fireman:
    description: FireManKit
    usage: "/fireman"
    permission: fire.command
  anchor:
    description: anchorKit
    usage: "/anchor"
    permission: anchor.command
  viper:
    description: ViperKit
    usage: "/viper"
    permission: viper.command
  fisherman:
    description: FishermanKit
    usage: "/fisherman"
    permission: fisherman.command
  launcher:
    description: LauncherKit
    usage: "/launcher"
    permission: launcher.command
permissions:
  stomper.command:
    description: "EnderMageKit"
    default: false
  endermage.command:
    description: "EnderMageKit"
    default: op
  kangaruu.command:
    description: "KangaruuKit"
    default: op
  switcher.command:
    description: "SwitcherKit"
    default: false
  urgal.command:
    description: "UrgalKit"
    default: op
  kits.command:
    description: "Kits"
    default: true
  miner.command:
    description: "MinerKit"
    default: op
  life.command:
    description: "LifeKit"
    default: op
  fireman.command:
    description: "FiremanKit"
    default: op
  anchor.command:
    description: "AnchorKit"
    default: op
  viper.command:
    description: "ViperKit"
    default: op
  fisherman.command:
    description: "FishermanKit"
    default: op
  launcher.command:
    description: "LauncherKit"
    default: op
  kangaruu.use.axe:
    description: "Gives player permission to use leap via axe!"
    default: true
  kangaruu.use.crouch:
    description: "Gives players permission to use leap via crouching in air!"
    default: true